version: "3.7"

services:
  mariadb:
    container_name: mariadb
    build:
     context: ./requirements/mariadb
    depends_on:
      - doppler
    volumes:
      - db:/var/lib/mysql
      - secrets:/tmp/.secrets
    networks:
      - app-network
    restart: on-failure

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
      - redis
      - doppler
    volumes:
      - wp:/var/www/html
      - secrets:/tmp/.secrets
    networks:
      - app-network
    restart: on-failure

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    restart: on-failure

  adminer:
    container_name: adminer
    build: ./bonus/adminer
    networks:
      - app-network
    depends_on:
      - mariadb
    restart: on-failure

  doppler:
    container_name: doppler
    build: ./bonus/doppler
    networks:
      - app-network
    environment:
      - DOPPLER_TOKEN=/run/secrets/auth_token
    secrets:
      - auth_token
    volumes:
      - secrets:/tmp/.secrets
    restart: on-failure

  ftp_server:
    container_name: ftp_server
    build: ./bonus/ftp_server
    depends_on:
      - wordpress
      - doppler
    ports:
      - "21:21"
    volumes:
      - wp:/var/www/html
      - secrets:/tmp/.secrets
    networks:
      - app-network
    restart: on-failure
  
  redis:
    container_name: redis
    build: ./bonus/redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/antgabri/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/antgabri/data/mariadb
  redis-data:
    driver: local
    name: redis-data
    driver_opts:
      type: none
      o: bind
      device: /home/antgabri/data/redis
  secrets:
    driver: local
    name: secrets
    driver_opts:
      type: none
      o: bind
      device: /home/antgabri/data/secrets

secrets:
  auth_token:
    file: /home/antgabri/data/token/doppler_token.txt