CREATE DATABASE IF NOT EXISTS mariadb;
CREATE USER IF NOT EXISTS 'antgabri'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON mariadb.* TO 'antgabri'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';