FROM debian:bullseye-slim


RUN apt-get -y update && apt-get -y upgrade && apt-get -y install nginx ssl-cert
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/sites-available/

RUN ln -s /etc/nginx/sites-available/default.conf /etc/nginx/sites-enabled/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]